# Generated by Django 2.1.7 on 2019-04-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='avl',
            new_name='Available',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='ds',
            new_name='Diseases',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='sl',
            new_name='Sl',
        ),
    ]
